name: Gacha pull on new Issue
on:
  issues:
    types: [opened]
    
jobs:
  job1:
    name: Sequence actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Record action to history
        run: |
          ISSUE="date +%s ${{ github.actor }} ${{ github.event.issue.title }}"
          echo $ISSUE >> ./action/history.txt
      - name: Execute script
        run: |
          python ./action/action.py
      - name: Commit report
        run: |
          git config --global user.name 'Ngan Nguyen'
          git config --global user.email 'ngantn1994@users.noreply.github.com'
          git commit -am "Automated report"
          git push