name: A workflow to test
on:
  issues:
    types: [opened]
    
jobs:
  build:
    name: Echo action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action
        with:
          seed: "1234"