name: Gacha pull on new Issue
on:
  issues:
    types: [opened]

jobs:
  job1:
    name: Sequence actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set env
        run: |
          echo "GACHA_SEED=$(date +"%s")" >> $GITHUB_ENV
      - name: Record action to history
        run: |
          SEED=${{ env.GACHA_SEED }}
          echo "GACHA_ID=$(echo "$SEED % 32" | bc)" >> $GITHUB_ENV
          ISSUE="$SEED,$(date +"%F %T"),${{ github.actor }},'${{ github.event.issue.title }}'"
          echo $ISSUE >> ./action/history.csv
      - name: Execute script
        run: |
          python ./action/action.py
      - name: Commit report
        run: |
          git config --global user.name 'Ngan Nguyen'
          git config --global user.email 'ngantn1994@users.noreply.github.com'
          git commit -am "Automated report"
          git push
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            <img src="https://ntuyetngan.com/public/github/readme-top.png">
            
            ### Thank you for waiting! Please have this dessert and come back for more!
            ${{ env.GACHA_ID }}
            
            <img src="https://ntuyetngan.com/public/github/readme-bottom.png">