name: A workflow to test
on:
  issues:
    types: [opened]
    
jobs:
  job1:
    name: Echo action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action
        with:
          seed: "1234"
          
  job2:
    name: Commit action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          {{ github.event.issue }} > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Ngan Nguyen'
          git config --global user.email 'ngantn1994@users.noreply.github.com'
          git commit -am "Automated report"
          git push